### ISSUE TITLE
ERROR: Type tuple() is not implicitly convertible to expected type contract OurToken.

### ISSUE THREAD

**Issue by Roccaaa** [Cyfrin/foundry-erc20-cu#10]
I'm having this error: 

Error (7407): Type tuple() is not implicitly convertible to expected type contract OurToken.
  --> test/OurTokenTest.t.sol:25:20:
   |
25 |         ourToken = deployer.run();
   |                    ^^^^^^^^^^^^^^

**this is the code:** 

//SPDX-License-Identifier: MIT

pragma solidity ^0.8.18;

import {Test} from "forge-std/Test.sol";
import {DeployOurToken} from "../script/DeployOurToken.s.sol";
import {OurToken} from "../src/OurToken.sol";

contract OurTokenTest  is Test {

    OurToken public ourToken;
    DeployOurToken public deployer;

    address bob = makeAddr("bob");
    address alice = makeAddr("alice");

    uint256 public constant STARTING_BALANCE = 100 ether;

    function setUp() public {
        
        deployer = new DeployOurToken();
        ourToken = deployer.run();

        vm.prank(msg.sender);
        ourToken.transfer(bob, STARTING_BALANCE);
        }

    function testBobBalance() public {
        assertEq(STARTING_BALANCE, ourToken.balanceOf(bob));
    }

}

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464

**Comment by Roccaaa** [comment]
Thanks for the reply, i'm new here and don't know where to ask things. Now
i should have posted it in the right place!

Have a good one

Rocco

Il giorno gio 10 ago 2023 alle ore 03:33 Patrick Collins <
***@***.***> ha scritto:
