### ISSUE TITLE
issue with the deploy script and test not being compatible with main erc20 contract that we have built

### ISSUE THREAD

**Issue by jmakwana0x1** [Cyfrin/foundry-erc20-cu#12]
below is the contract we are building on 
pragma solidity 0.8.24;

```solidity
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract OurToken is ERC20 {
    constructor() ERC20("OurToken", "OT") {
        _mint(msg.sender, 100e18);
    }
}
```

it doesn't expect intial supply but in deploy script and test script we are passing intial supply 

```solidity
        OurToken ourToken = new OurToken(INITIAL_SUPPLY);
```

**Comment by cromewar** [comment]
Hello @jmakwana01, yes, you are right. The current version does not take a constructor parameter and it's causing errors, I'm submitting a fix for this ASAP.

Thanks for your contribution.

**Comment by cromewar** [comment]
Update issue solved on this PR
https://github.com/Cyfrin/foundry-erc20-cu/pull/13

thanks again @jmakwana01
